MusicWebsite/Models/MusicPiece.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicPiece
    {
        public int RecordNumber { get; set; }
        public int NamingConventionID { get; set; }
        public int ComposerID { get; set; }
        public Nullable<int> Difficulty { get; set; }
        public Nullable<int> Year { get; set; }
        public string Instrument { get; set; }
    
        public virtual Composer Composer { get; set; }
        public virtual OpusNamingConvention OpusNamingConvention { get; set; }
    }
}

MusicWebsite/Controllers/MusicPiecesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using MusicWebsite.classes;
using MusicWebsite.Models;
using MusicWebsite.ViewModels;

namespace MusicWebsite.Controllers
{
    public class MusicPiecesController : BaseController
    {
        //private SheetMusicEntities db = new SheetMusicEntities();

        // GET: MusicPieces
        public ActionResult Index()
        {
            var musicPieces = dal.DbContext.MusicPieces.Include(m => m.Composer).Include(m => m.OpusNamingConvention);
            setFilters(0, 0, 0);
            return View(musicPieces.ToList());
        }

        private void setFilters(int composerDefault = 0, int yearDefault = 0, int levelDefault = 0)
        {
            List<ListItem> compItems = new List<ListItem>();
            var compList = dal.DbContext.Composers.ToList();
            compItems = compList.Select(s => new ListItem(s.FirstName + ' ' + s.LastName, s.ComposerID.ToString())).ToList();
            compItems.Insert(0, new ListItem("All", ""));
            SelectList compSelectList = new SelectList(compItems, "Value", "Text", composerDefault > 0 ? composerDefault.ToString() : null);
            ViewBag.ComposerFilter = compSelectList;

            List<ListItem> yearsItems = new List<ListItem>();
            var yearsList = dal.DbContext.MusicPieces.Where(w => w.Year != null).Select(s => new { MusicYear = (int)s.Year }).Distinct().ToList();
            yearsItems = yearsList.Select(s => new ListItem(s.MusicYear.ToString(), s.MusicYear.ToString())).ToList();
            yearsItems.Insert(0, new ListItem("All", ""));
            SelectList yearsSelectList = new SelectList(yearsItems, "Value", "Text", yearDefault > 0 ? yearDefault.ToString() : null);
            ViewBag.YearFilter = yearsSelectList;

            List<ListItem> diffItems = new List<ListItem>();
            var diffList = dal.DbContext.MusicPieces.Where(w => w.Difficulty != null).Select(s => new { MusicDifficulty = (int)s.Difficulty }).Distinct().ToList();
            diffItems = diffList.Select(s => new ListItem(s.MusicDifficulty.ToString(), s.MusicDifficulty.ToString())).ToList();
            diffItems.Insert(0, new ListItem("All", ""));
            SelectList difficultySelectList = new SelectList(diffItems, "Value", "Text", levelDefault > 0 ? levelDefault.ToString() : null);
            ViewBag.DifficultyFilter = difficultySelectList;
        }

        /// <summary>
        /// AJAX method to query the music pieces table
        /// </summary>
        /// <param name="p"></param>
        /// <returns></returns>
        public JsonResult GetPieces(MusicTableParameters p)
        {
            try
            {
                IQueryable<view_MusicPieces> raw = (from d in this.dal.DbContext.view_MusicPieces
                                           where 
                                                (p.ComposerID == 0 || d.ComposerID == p.ComposerID) &&
                                                (p.Year == 0 || p.Year == d.Year) &&
                                                (p.Difficulty == 0 || p.Difficulty == d.Difficulty) &&
                                                (p.Search.Value == null || 
                                                ((d.FullName.Contains(p.Search.Value)) || d.PieceName.Contains(p.Search.Value)))
                                           select d)
               .AsQueryable();

                switch (p.Columns[p.Order[0].Column].Data)
                {
                    case "LastName":
                        if (p.Order[0].Dir == DataTableViewModel.DataTablesOrderDir.DESC)
                            raw = raw.OrderByDescending(o => o.LastName);
                        else
                            raw = raw.OrderBy(o => o.LastName);
                        break;
                    case "FirstName":
                        if (p.Order[0].Dir == DataTableViewModel.DataTablesOrderDir.DESC)
                            raw = raw.OrderByDescending(o => o.FirstName);
                        else
                            raw = raw.OrderBy(o => o.FirstName);
                        break;
                    case "PieceName":
                        if (p.Order[0].Dir == DataTableViewModel.DataTablesOrderDir.DESC)
                            raw = raw.OrderByDescending(o => o.PieceName);
                        else
                            raw = raw.OrderBy(o => o.PieceName);
                        break;
                    case "Instrument":
                        if (p.Order[0].Dir == DataTableViewModel.DataTablesOrderDir.DESC)
                            raw = raw.OrderByDescending(o => o.Instrument);
                        else
                            raw = raw.OrderBy(o => o.Instrument);
                        break;

                    default:
                        raw = raw.SortBy(p.SortOrder);
                        break;
                }
                List<view_MusicPieces> parsedResults;
                if (p.Length > 0)
                    parsedResults = raw.Skip(p.Start).Take(p.Length).ToList();
                else
                    parsedResults = raw.ToList();
                var data = parsedResults.Select(s => new MusicGridViewModel(s)).ToList();
                var totalCount = raw.Count();
                DataTableViewModel.DataTablesResult<MusicGridViewModel> result = new DataTableViewModel.DataTablesResult<MusicGridViewModel>()
                {
                    draw = p.Draw,
                    recordsFiltered = totalCount,
                    recordsTotal = totalCount,
                    data = data
                };

                return Json(result);
            }
            catch (Exception e)
            {
                return Json(new { error = e.Message });
            }

        }

        // GET: MusicPieces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicPiece musicPiece = dal.DbContext.MusicPieces.Find(id);
            if (musicPiece == null)
            {
                return HttpNotFound();
            }
            return View(musicPiece);
        }

        //GET: Hover agent
        public ActionResult HoverAgent(int? id)
        {
            Composer composerDetails = dal.DbContext.Composers.Find(id);
            if (composerDetails == null)
            {
                return HttpNotFound();
            }
            return View(composerDetails);
        }

        // GET: MusicPieces/Create
        public ActionResult Create()
        {
            ViewBag.ComposerID = new SelectList(dal.DbContext.Composers, "ComposerID", "FirstName");
            ViewBag.NamingConventionID = new SelectList(dal.DbContext.OpusNamingConventions, "NamingConventionID", "PieceType");
            return View();
        }

        // POST: MusicPieces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecordNumber,NamingConventionID,ComposerID,Difficulty,Year")] MusicPiece musicPiece)
        {
            if (ModelState.IsValid)
            {
                dal.DbContext.MusicPieces.Add(musicPiece);
                dal.DbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ComposerID = new SelectList(dal.DbContext.Composers, "ComposerID", "FirstName", musicPiece.ComposerID);
            ViewBag.NamingConventionID = new SelectList(dal.DbContext.OpusNamingConventions, "NamingConventionID", "PieceType", musicPiece.NamingConventionID);
            return View(musicPiece);
        }

        // GET: MusicPieces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicPiece musicPiece = dal.DbContext.MusicPieces.Find(id);
            if (musicPiece == null)
            {
                return HttpNotFound();
            }
            ViewBag.ComposerID = new SelectList(dal.DbContext.Composers, "ComposerID", "FirstName", musicPiece.ComposerID);
            ViewBag.NamingConventionID = new SelectList(dal.DbContext.OpusNamingConventions, "NamingConventionID", "PieceType", musicPiece.NamingConventionID);
            return View(musicPiece);
        }

        // POST: MusicPieces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RecordNumber,NamingConventionID,ComposerID,Difficulty,Year")] MusicPiece musicPiece)
        {
            if (ModelState.IsValid)
            {
                dal.DbContext.Entry(musicPiece).State = EntityState.Modified;
                dal.DbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ComposerID = new SelectList(dal.DbContext.Composers, "ComposerID", "FirstName", musicPiece.ComposerID);
            ViewBag.NamingConventionID = new SelectList(dal.DbContext.OpusNamingConventions, "NamingConventionID", "PieceType", musicPiece.NamingConventionID);
            return View(musicPiece);
        }

        // GET: MusicPieces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

MusicWebsite/Views/MusicPieces/Create.cshtml
@model MusicWebsite.Models.MusicPiece

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MusicPiece</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RecordNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecordNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecordNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamingConventionID, "NamingConventionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NamingConventionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NamingConventionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComposerID, "ComposerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ComposerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ComposerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Difficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Difficulty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Difficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicWebsite/Views/MusicPieces/Delete.cshtml
@model MusicWebsite.Models.MusicPiece

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusicPiece</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpusNamingConvention.PieceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpusNamingConvention.PieceType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MusicWebsite/Views/MusicPieces/Details.cshtml
@model MusicWebsite.Models.MusicPiece

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MusicPiece</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpusNamingConvention.PieceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpusNamingConvention.PieceType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RecordNumber }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MusicWebsite/Views/MusicPieces/Edit.cshtml
@model MusicWebsite.Models.MusicPiece

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MusicPiece</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecordNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.NamingConventionID, "NamingConventionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NamingConventionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NamingConventionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComposerID, "ComposerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ComposerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ComposerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Difficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Difficulty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Difficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicWebsite/Views/MusicPieces/Index.cshtml
@model IEnumerable<MusicWebsite.Models.MusicPiece>

@{
    ViewBag.Title = "Music Pieces";
}

<h2>Music Records</h2>
<script language="Javascript" type="text/javascript">
    $(document).ready(function () {
        baseImagePath = '@Url.Content("~/images")';
        var dtTable = $('#dtTable').DataTable({
            lengthMenu: [[10, 25, 50, 100, 200], [10, 25, 50, 100, 200]],
            iDisplayLength: 50,
            serverSide: true,
            ajax: {
                url: '@Url.Action("GetPieces", "MusicPieces", null, Request.IsSecureConnection ? "https" : "http")',
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: function (data) {
                    return data = JSON.stringify($.extend({},
                        data, {
                            temp: new Date().getTime() / 1000,
                            ComposerID: $("#ComposerFilter").val(),
                            Year: $("#YearFilter").val(),
                            Difficulty: $("#DifficultyFilter").val(),
                        }
                    ));
                }
            },
            processing: true,
            paging: true,
            order: [[0, "desc"]],
            deferRender: true,

            columns: [
                {
                    "data": "PieceName",
                },
                {
                    "data": "FirstName",
                },
                {
                    "data": "LastName",
                },
                {
                    "data": "Year",
                },
                {
                    "data": "Difficulty",
                },
                {
                    "data": "Instrument",
                },
            ],
        });

        $("#ComposerFilter").change(function () {
            if (dtTable)
                dtTable.ajax.reload();
        });

        $("#YearFilter").change(function () {
            if (dtTable)
                dtTable.ajax.reload();
        });

        $("#DifficultyFilter").change(function () {
            if (dtTable)
                dtTable.ajax.reload();
        });

        $(window).resize(function () {
            //dtTable.draw();
        });

    });
</script>

<div class="row filter-search-none">
    <div class="col-sm-12">
        <div class="moveplchld" style="margin-top:0px;">
            <table>
                <tr>
                    <td><label for="ComposerFilter">Composer @Html.DropDownList("ComposerFilter", ViewBag.ComposerFilter as List<SelectListItem>, new { @class = "form-control", @style = "font-size:12px;height:28px;" })</label></td>
                    <td>&nbsp;&nbsp;<label for="YearFilter">Year @Html.DropDownList("YearFilter", ViewBag.YearFilter as List<SelectListItem>, new { @class = "form-control", @style = "font-size:12px;height:28px;" })</label></td>
                    <td>&nbsp;&nbsp;<label for="DifficultyFilter">Difficulty Level @Html.DropDownList("DifficultyFilter", ViewBag.DifficultyFilter as List<SelectListItem>, new { @class = "form-control", @style = "font-size:12px;height:28px;" })</label></td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<table id="dtTable" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th>
                Piece Name
            </th>
            <th>
                Composer First Name
            </th>
            <th>
                Composer Last Name
            </th>
            <th>
                Year
            </th>
            <th>
                Difficulty
            </th>
            <th>
                Instrument
            </th>

        </tr>
    </thead>
    <tbody></tbody>
</table>

@*this creates a data table with edit capabilities*@
@*
<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Difficulty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Composer.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OpusNamingConvention.PieceType)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Composer.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpusNamingConvention.PieceType)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RecordNumber })
            </td>
        </tr>
    }

    </table>*@